FROM ubuntu:trusty
MAINTAINER bung@slac.stanford.edu

RUN apt-get --assume-yes update && apt-get --assume-yes install wget dpkg-dev cmake g++ gcc binutils libx11-dev libxpm-dev libxft-dev libxext-dev build-essential make python python-dev libcxxtools-dev git git-svn libfftw3-dev libmysqlclient-dev vim patch

WORKDIR /SOFTWARE/
RUN wget -q https://root.cern.ch/download/root_v5.34.36.source.tar.gz && tar xf root_v5.34.36.source.tar.gz
WORKDIR /SOFTWARE/root
RUN ls
RUN pwd
RUN sh ./configure --disable-xml --disable-fftw3 --enable-builtin-pcre --enable-builtin-freetype --disable-roofit --disable-krb5 --disable-ssl --enable-python --enable-soversion
RUN make -j2

WORKDIR /SOFTWARE/clhep/
RUN wget -q https://proj-clhep.web.cern.ch/proj-clhep/dist1/clhep-2.0.4.5.tgz && \
    tar xf clhep-2.0.4.5.tgz && \
    rm clhep-2.0.4.5.tgz
WORKDIR /SOFTWARE/clhep/2.0.4.5/CLHEP
RUN ls
RUN ./configure --prefix /SOFTWARE/clhep/2.0.4.5/ && \
    make && \
    make install

WORKDIR /SOFTWARE/
RUN wget -q http://cern.ch/geant4-data/releases/geant4.9.3.p02.tar.gz && \
    tar xf geant4.9.3.p02.tar.gz && \
    rm geant4.9.3.p02.tar.gz

WORKDIR /SOFTWARE/geant4.9.3.p02/data
RUN wget -q http://cern.ch/geant4-data/datasets/PhotonEvaporation.2.0.tar.gz && tar xf PhotonEvaporation.2.0.tar.gz && \
    wget -q http://cern.ch/geant4-data/datasets/G4NDL.3.13.tar.gz && tar xf G4NDL.3.13.tar.gz && \
    wget -q http://cern.ch/geant4-data/datasets/G4EMLOW.6.9.tar.gz && tar xf G4EMLOW.6.9.tar.gz && \
    wget -q http://cern.ch/geant4-data/datasets/G4RadioactiveDecay.3.2.tar.gz && tar xf G4RadioactiveDecay.3.2.tar.gz && \
    wget -q http://cern.ch/geant4-data/datasets/G4ABLA.3.0.tar.gz && tar xf G4ABLA.3.0.tar.gz && \
    wget -q http://cern.ch/geant4-data/datasets/RealSurface.1.0.tar.gz && tar xf RealSurface.1.0.tar.gz && \
    rm -f *.tar.gz
WORKDIR /SOFTWARE/geant4.9.3.p02
ADD config.sh_ubuntu /SOFTWARE/g4config.sh
ADD Configure_dockerized Configure
RUN ["./Configure", "-f", "/SOFTWARE/g4config.sh", "-d", "-e", "-r", "-build"]
RUN ./Configure && \
    cp $PWD/.config/bin/Linux-g++/env.sh . && \
    /bin/sh ./env.sh
